# Generated by Django 5.0.7 on 2024-09-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_student_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='student',
            table='members_student',
        ),
    ]
