# Generated by Django 5.0.7 on 2024-10-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_student_id_alter_student_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='2022-2026', max_length=255),
        ),
    ]
