# Generated by Django 5.0.7 on 2024-10-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_student_linkedin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='github_id',
            field=models.CharField(default='No address provided', max_length=255),
        ),
    ]
